### ISSUE TITLE
Knulli / retrobat

### ISSUE THREAD

**Issue by ajmandourah** [anthonycaccese/minui-menu-es-de#1]
Hey.

This is really clean. Thanks for your effort. 

I wonder if this can be ported to ES in batocera like knulli and such . I looked around in their themeing structure and it seems difficult . one option is to use a grid but i am not sure (mainly for system view as there is no system list in batocera version )

what do you think ?

**Comment by anthonycaccese** [comment]
I would prefer to keep it in a list structure to make sure it tries to stay as close as possible to the source it was inspired by... otherwise I am not sure it could be called MinUI Menu =)

Bato may have added the ability to use textlists on system view but its not documented yet so I haven't been able to check.  Also there are a bunch of ES-DE theme engine features used in this theme that I am not sure Bato would support so that would require some digging.

**Comment by anthonycaccese** [comment]
Realized I didn't say... I do want to explore it =)

Its on my list just not sure when I will get to it.

**Comment by ajmandourah** [comment]
> I would prefer to keep it in a list structure to make sure it tries to stay as close as possible to the source it was inspired by... otherwise I am not sure it could be called MinUI Menu =)
> 
> Bato may have added the ability to use textlists on system view but its not documented yet so I haven't been able to check. Also there are a bunch of ES-DE theme engine features used in this theme that I am not sure Bato would support so that would require some digging.

this sounds great. from where did you get the information that they have implemented textlist in system view? this is great as it will help creating minimalistic themes. 

I dunno if you have experimented with grids. I haven't but im kinda optimistic . a 1x10 grid theoritically can create a list. 

we will see. 

Thanks for your time

**Comment by anthonycaccese** [comment]
I saw it in this PR: https://github.com/batocera-linux/batocera-emulationstation/pull/1657

**Comment by ajmandourah** [comment]
reading the cpp code in the pr I have succeded in getting a text list system view. I will try to somehow port your theme  to batocera in general .
I must say the tags were non intuitive.
its mainly using this in a system view 
```
<textlist name="textlist">
```

**Comment by anthonycaccese** [comment]
sorry I am not sure I follow what you mean by "I must say the tags were non intuitive."

**Comment by ajmandourah** [comment]
It's just seems weird where other text lists named "gamelist". This should be named system list for example

**Comment by anthonycaccese** [comment]
odd, usually the name value can be whatever you like.  will close this for now as an active item, we can continue to discuss here though.

**Comment by 6isss** [comment]
391 days later 🙄 would be nice having it on Knulli, with the option of making some UI transparent 

![Image](https://github.com/user-attachments/assets/f95c59bd-7ab6-4501-b530-a47110ade423)

**Comment by anthonycaccese** [comment]
@6isss sadly Its not that straightforward to port this theme to Bato/Knulli as the theme engine those use does not support some of the things that ES-DE does... so yeah it may happen but not something I would look at soon.  Glad to answer any questions you have if you were interested in trying to port it though.
