### ISSUE TITLE
Custom Color Scheme: [Fallout]

### ISSUE THREAD

**Issue by RobZombie9043** [anthonycaccese/minui-menu-es-de#2]
![Vault Boy 4-3](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/63e0dc9e-d43c-444d-b126-5d0df9a1aa83)

[theme-customizations.zip](https://github.com/user-attachments/files/15981263/theme-customizations.zip)

**Comment by anthonycaccese** [comment]
this looks awesome, wondering if I should add the ability to customize the coloring of the boxart/screenshots when those are turned on too.  in the case of the fallout color scheme thinking that could get things to mesh well when those views are used.  what do you think?

**Comment by RobZombie9043** [comment]
Yeah that sounds like it could work nicely. I didn’t really try to use either of the media variants as it looked a bit weird by default.

**Comment by RobZombie9043** [comment]
Yeah it looks quite good, with saturation 0 and colorized.
I think I need to reconsider having vault boy there, he is still getting in the way!

![Capture](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/e6940987-8b6b-4c00-909e-270e4600ff36)

**Comment by RobZombie9043** [comment]
Yeah, better without the vault boy.
The screenshot variant actually looks amazing colorized like that.

Let me know if you decide to add in those properties and I can re-upload the files.

| List + Screenshot (1:1) | List + Screenshot (4:3) |
|----|----|
| ![Capture3](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/4ebe7433-e208-469b-adb0-f5b2c7e48068) | ![Capture2](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/57018f82-1a12-4ae8-92e7-dff5e08e15fd) |

**Comment by anthonycaccese** [comment]
oh wow yeah that looks awesome and yeah looking at it without the vault boy graphic i think it looks cleaner too

here are the new props i just added based on this:
```
<gameArtColor>ffffff</gameArtColor>
<gameArtSaturation>1</gameArtSaturation>
<gameArtBrightness>0</gameArtBrightness>
<gameArtCornerRadius>0.02</gameArtCornerRadius>
```

**Comment by RobZombie9043** [comment]
Thank you, here are the updated files.

[theme-customizations.zip](https://github.com/user-attachments/files/16019282/theme-customizations.zip)

| System | List + Boxart | List + Screenshot | 
|----|----|----|
| ![Capture-System-4-3](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/43800613-5a05-4250-b0ef-e8942a42f5cc) | ![Capture-gamelist+boxart-4-3](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/4e7e2617-b701-4dcb-addd-52b9599cf051) | ![Capture-gamelist+screenshot-4-3](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/b86dcaaf-16d9-407f-b584-7a0361412483) |

**Comment by anthonycaccese** [comment]
thank you so much, I just added your color scheme to the main theme now
