### ISSUE TITLE
Custom Color Scheme: [Game Boy DMG]

### ISSUE THREAD

**Issue by RobZombie9043** [anthonycaccese/minui-menu-es-de#3]
Hi Ant, here is the GB color scheme. Happy to take on board any suggestions.

[theme-customizations.zip](https://github.com/user-attachments/files/16038378/theme-customizations.zip)

| System | List + Boxart | List + Screenshot | 
|----|----|----|
| ![GB-system](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/f01eceaa-35d5-4cf4-bb4a-3dbaac49e69e) | ![GB-list+boxart](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/1253e184-941a-4f82-8a53-23e8b6d03ade) | ![GB-list+screenshot](https://github.com/anthonycaccese/minui-menu-es-de/assets/77545967/9312180d-1786-473a-9162-c4079b12b6df) |

**Comment by anthonycaccese** [comment]
Added!
